headers: Add CLSIDs in mfidl.idl
Required for chromium.

chromium/media/gpu/windows/dxva_video_decode_accelerator_win.cc:1477:15:
error: use of undeclared identifier 'CLSID_MSVPxDecoder'

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>