crt: Add _imp_ symbols for __getmainargs() and __wgetmainargs() functions
They were accidentally removed in commit e0b9e84fd8f9 ("crt: Fix
__getmainargs() and __wgetmainargs() ABI for msvcrt40.dll and msvcrt.dll")
when these functions were implemented as wrappers around the real
functions.

_imp_ symbols for __getmainargs() and __wgetmainargs() functions are needed
for applications which provides own declaration of these functions with
__declspec(dllimport).

Fixes linking error "undefined reference to `_imp____wgetmainargs'" as was
reported in bug report for mpeg123 application:
https://github.com/mingw-w64/mingw-w64/issues/73