headers: Define missing PHYSICAL_ADDRESS type in ntddser.h
This fixes the following compiler error in chromium.

ntddser.h: At global scope:
ntddser.h:368:9: error: 'PHYSICAL_ADDRESS' does not name a type; did you mean 'PNC_ADDRESS'?
  368 |         PHYSICAL_ADDRESS  PortAddress;
      |         ^~~~~~~~~~~~~~~~
      |         PNC_ADDRESS

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>