headers: Fix some data types in qos2.h
Define QOS_FLOWID before it is used. This fixes the following errors.

In file included from ../../../../../b/src/3rdparty/chromium/net/socket/udp_socket_win.h:14:
qos2.h:87:3: error: unknown type name 'PQOS_FLOWID'
  PQOS_FLOWID FlowId
  ^
qos2.h:112:3: error: unknown type name 'QOS_FLOWID'
  QOS_FLOWID FlowId,
  ^

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>