headers: Disable conflicting OLE methods on Cygwin
On inclusion of the header `comutil.h` on Cygwin platforms errors such
as:

include/comutil.h:413:3: error: '_variant_t::_variant_t(unsigned int)' cannot be overloaded with '_variant_t::_variant_t(unsigned int)'

, are produced because on Cygwin some methods are duplicates via a type
alias.

Disable these methods under `__CYGWIN__`.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>