headers: Add more macros for wide-char APIs in _dbg_common.h
This is required for rpcs3 project which defines DBGHELP_TRANSLATE_TCHAR.
Also this fixes the following compiler error.

error: cannot convert 'CHAR*' {aka 'char*'} to 'LPWSTR' {aka 'wchar_t*'}
error: 'SymGetLineFromAddrW' was not declared in this scope

Signed-off-by: Biswapriyo Nath <nathbappai@gmail.com>
Signed-off-by: LIU Hao <lh_mouse@126.com>