ssp: fix `__stack_chk_guard` type
In https://gcc.gnu.org/PR121911 `gcc` started enforcing the type of
`__stack_chk_guard` to `uintptr_t` and broke `mingw-w64` build as:

```
ssp/stack_chk_guard.c:11:7: error: conflicting types for '__stack_chk_guard'; have 'void *'
   11 | void *__stack_chk_guard;
      |       ^~~~~~~~~~~~~~~~~
cc1: note: previous declaration of '__stack_chk_guard' with type 'long long unsigned int'
ssp/stack_chk_guard.c:11:7: warning: declaration of '__stack_chk_guard' shadows a global declaration [-Wshadow]
   11 | void *__stack_chk_guard;
      |       ^~~~~~~~~~~~~~~~~
```

Let's match the declaration to unsigned type as suggested by upstream in
https://gcc.gnu.org/PR121911#c6.